wal_level = logical
max_replication_slots = 10
max_wal_senders = 10
max_slot_wal_keep_size = '8GB'
synchronous_commit = on
track_commit_timestamp = on
archive_mode = on
archive_command = 'test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f'
archive_timeout = '60s'
