CREATE SCHEMA IF NOT EXISTS event_store AUTHORIZATION event_store_owner;
CREATE SCHEMA IF NOT EXISTS projection_runtime AUTHORIZATION event_store_owner;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA event_store;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE event_store FROM PUBLIC;
