bootstrap.servers=kafka-1:9092,kafka-2:9092,kafka-3:9092
group.id=event-store-connect
config.storage.topic=_connect-event-store-configs
offset.storage.topic=_connect-event-store-offsets
status.storage.topic=_connect-event-store-status
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
header.converter=org.apache.kafka.connect.storage.SimpleHeaderConverter
exactly.once.source.support=enabled
topic.creation.enable=false
producer.acks=all
producer.enable.idempotence=true
producer.linger.ms=0
producer.max.in.flight.requests.per.connection=5
producer.compression.type=lz4
consumer.isolation.level=read_committed
